# Generated by Django 6.0.4 on 2026-04-29 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Katagoriya nomi')),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Maxsulot nomi')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Maxsulot narxi')),
                ('image', models.ImageField(upload_to='products/', verbose_name='Maxsulot rasmi')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Tarif')),
                ('is_available', models.BooleanField(default=True, verbose_name="bormi_yo'q")),
                ('in_stock', models.IntegerField(default=1, verbose_name='Ombordagi soni')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.category')),
            ],
        ),
    ]
