# Generated by Django 6.0.4 on 2026-04-21 16:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catagory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Katagoriya nomi')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Maxsulot nomi')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Maxsulot narxi')),
                ('image', models.ImageField(upload_to='products/', verbose_name='Maxsulot rasmi')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Maxsulot tarifi')),
                ('in_stock', models.IntegerField(default=1, verbose_name='Ombordagi soni')),
                ('catagory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_main.catagory')),
            ],
        ),
    ]
